language: php
sudo: required
dist: trusty
group: edge
php:
  - 7.0

before_script:
- sudo apt-get install -y screen
- make install
- cp config.php.dist config.php
- screen -dm php server.php

script:
- phpunit --stop-on-error --stop-on-failure -d memory_limit=2560M
