language: php

php:
  - 7.0

before_script:
- make install
- cp config.php.dist config.php
- screen php server.php

script:
- phpunit --testsuite $TEST_SUITE --stop-on-error --stop-on-failure -d memory_limit=2560M
