language: php

php:
  - 5.5

env:
  matrix:
    - TEST_SUITE="unit"
    - TEST_SUITE="integration"
    - TEST_SUITE="slow"

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache


before_script:
- make install
- cp config.php.dist config.php
- php server.php
script:
- phpunit --testsuite $TEST_SUITE --stop-on-error --stop-on-failure -d memory_limit=2560M
